### ISSUE TITLE
点击F10运行以后报错

### ISSUE THREAD

**Issue by smallmj** [1492949083/ZenlessZoneZero-Snake#1]
D:\ZenlessZoneZero-Snake>python start.py
F10 键启动
F11 键暂停
Ctrl+C 键退出
脚本开始运行！
Exception in thread Thread-4 (click_over_img):
Traceback (most recent call last):
  File "C:\Program Files\Python\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ZenlessZoneZero-Snake\start.py", line 103, in click_over_img
    img = pyg.locateCenterOnScreen("image.png", confidence=0.8, region=(left_top_x, left_top_y, right_bottom_x, right_bottom_y))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Lib\site-packages\pyautogui\__init__.py", line 228, in _couldNotImportPyScreeze
    raise PyAutoGUIException(
pyautogui.PyAutoGUIException: PyAutoGUI was unable to import pyscreeze. (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.

**Comment by ccc007ccc** [comment]
尝试 `pip install --upgrade pyautogui pillow pyscreeze` ，也可以使用release里打包好的exe

**Comment by smallmj** [comment]
upgrade以后是不报错了，但是按了F10以后在游戏中没效果啊

**Comment by ccc007ccc** [comment]
> upgrade以后是不报错了，但是按了F10以后在游戏中没效果啊

需要用管理员权限运行

**Comment by smallmj** [comment]
![image](https://github.com/user-attachments/assets/21e932a0-864b-4bf4-9733-2aa01605edb6)
是管理员权限，还是不行，游戏中没反应，而且按ctrl+c以后报错

**Comment by ccc007ccc** [comment]
> ![image](https://private-user-images.githubusercontent.com/23742160/358521559-21e932a0-864b-4bf4-9733-2aa01605edb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTk0NDMsIm5iZiI6MTcyMzc5OTE0MywicGF0aCI6Ii8yMzc0MjE2MC8zNTg1MjE1NTktMjFlOTMyYTAtODY0Yi00YmY0LTk3MzMtMmFhMDE2MDVlZGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA5MDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzM2Q0MThhMGVlZmZkMjg3ZWY1ZTZhMmFkNDY2MGVjNGVjZjA5MmMyNGQwMGNjOGI5M2UzYTg5NzkyZWUyNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O7_gV352tUJs1p3ps96HX1jrHzmpZ1-RYAXG_HIr338) 是管理员权限，还是不行，游戏中没反应，而且按ctrl+c以后报错

因为我写的是检测到游戏失败的画面才开始操作,现在我已经改成了按F10就直接操作了, `git pull` 更新代码就可以用了
或者你可以用你现在的脚本在游戏结束画面按F10开始脚本,就不用更新代码了

ctrl + c 报错是正常的,报错后就退出了

这个脚本使用时需要在键盘模式,
