### ISSUE TITLE
远程桌面运行提示没有键盘

### ISSUE THREAD

**Issue by smallmj** [1492949083/ZenlessZoneZero-Snake#2]
c:\zzz\ZenlessZoneZero-Snake>python start.py
Traceback (most recent call last):
  File "c:\zzz\ZenlessZoneZero-Snake\start.py", line 1, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

**Comment by ccc007ccc** [comment]
尝试 `pip install -r requirements.txt`
或者 `pip install keyboard`

**Comment by smallmj** [comment]
已经安装了keyboard还是提示没有这个模块。。。

c:\zzz\ZenlessZoneZero-Snake>python start.py
Traceback (most recent call last):
  File "c:\zzz\ZenlessZoneZero-Snake\start.py", line 1, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

c:\zzz\ZenlessZoneZero-Snake>pip show keyboard
Name: keyboard
Version: 0.13.5
Summary: Hook and simulate keyboard events on Windows and Linux
Home-page: https://github.com/boppreh/keyboard
Author: BoppreH
Author-email: boppreh@gmail.com
License: MIT
Location: C:\ProgramData\anaconda3\Lib\site-packages
Requires:
Required-by:

**Comment by ccc007ccc** [comment]
> 已经安装了keyboard还是提示没有这个模块。。。
> 
> c:\zzz\ZenlessZoneZero-Snake>python start.py Traceback (most recent call last): File "c:\zzz\ZenlessZoneZero-Snake\start.py", line 1, in import keyboard ModuleNotFoundError: No module named 'keyboard'
> 
> c:\zzz\ZenlessZoneZero-Snake>pip show keyboard Name: keyboard Version: 0.13.5 Summary: Hook and simulate keyboard events on Windows and Linux Home-page: https://github.com/boppreh/keyboard Author: BoppreH Author-email: [boppreh@gmail.com](mailto:boppreh@gmail.com) License: MIT Location: C:\ProgramData\anaconda3\Lib\site-packages Requires: Required-by:

可能你的python和pip指向的不是同一个环境,尝试使用 `python -m pip install -r requirements.txt` 安装依赖或者使用打包好的exe
